goals:
  rec_pose_1:
    position:
    - 3.721
    - 4.059
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.927
    - 0.376
  rec_pose_2:
    position:
    - 0.5
    - 4.5
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  rec_pose_3:
    position:
    - 2.5
    - 2.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 1.0
    - 0.0
  rec_pose_4:
    position:
    - 2.5
    - 4.5
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 1.0
    - 0.0
  pickup_pose:
    position:
    - 0.0
    - 0.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  place_pose_A:
    position:
    - 0.0
    - 0.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  place_pose_B:
    position:
    - 0.0
    - 0.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  place_pose_C:
    position:
    - 0.0
    - 0.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
  place_pose_D:
    position:
    - 0.0
    - 0.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
waypoints:
  obs_start:
    position:
    - 5.7
    - 0.811
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 1.0
    - 0.011
  obs_end:
    position:
    - 0.5
    - 0.75
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 1.0
    - 0.0
sequences:
  recognition:
  - rec_pose_1
  - rec_pose_2
  - rec_pose_4
  - rec_pose_3
  obstacle_test:
  - obs_start
  - obs_end
  pick_place:
    pickup: pickup_pose
    places:
      A: place_pose_A
      B: place_pose_B
      C: place_pose_C
      D: place_pose_D
