goals:
  rec_pose_1:
    position:
    - 3.721
    - 4.059
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.927
    - 0.376
  rec_pose_2:
    position:
    - 3.723
    - 5.411
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - -0.916
    - 0.401
  rec_pose_3:
    position:
    - 3.868
    - 5.265
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.338
    - 0.941
  rec_pose_4:
    position:
    - 3.292
    - 2.731
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.36
    - 0.933
  pickup_pose:
    position:
    - 2.675
    - 4.871
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - -0.847
    - 0.531
  place_pose_A:
    position:
    - 3.222
    - 6.985
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.496
    - 0.868
  place_pose_B:
    position:
    - 3.648
    - 6.695
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.47
    - 0.883
  place_pose_C:
    position:
    - 4.085
    - 6.426
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.501
    - 0.865
  place_pose_D:
    position:
    - 0.0
    - 0.0
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.0
    - 1.0
waypoints:
  obs_start:
    position:
    - 5.7
    - 0.811
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 1.0
    - 0.011
  obs_end:
    position:
    - 2.729
    - 1.289
    - 0.0
    orientation:
    - 0.0
    - 0.0
    - 0.098
    - 0.995
sequences:
  recognition:
  - rec_pose_1
  - rec_pose_2
  - rec_pose_4
  - rec_pose_3
  obstacle_test:
  - obs_start
  - obs_end
  pick_place:
    pickup: pickup_pose
    places:
      A: place_pose_A
      B: place_pose_B
      C: place_pose_C
      D: place_pose_D
